=== microsoft/azure-pipelines-tasks/tasks.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "VSTS Tasks schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "description": "A unique guid for this task",
      "pattern": "^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$"
    },
    "name": {
      "type": "string",
      "description": "Name with no spaces",
      "pattern": "^[A-Za-z0-9\\-]+$"
    },
    "friendlyName": {
      "type": "string",
      "description": "Descriptive name (spaces allowed)"
    },
    "description": {
      "type": "string",
      "description": "Detailed description of what your task does"
    },
    "helpMarkDown": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "visibility": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Build",
          "Release",
          "Preview"
        ]
      }
    },
    "runsOn": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Agent",
          "MachineGroup",
          "Server"
        ]
      }
    },
    "category": {
      "type": "string",
      "description": "Where the task appears in VSTS",
      "enum": [
        "Build",
        "Utility",
        "Test",
        "Package",
        "Deploy"
      ]
    },
    "groups": {
      "type": "array",
      "description": "Describes groups that task properties may be logically grouped by in the UI.",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "displayName"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "displayName": {
            "type": "string"
          },
          "isExpanded": {
            "type": "boolean"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "Preview"
              ]
            }
          }
        }
      }
    },
    "demands": {
      "type": "array",
      "description": "Allows you to define a list of demands that a build agent requires to run this build task.",
      "items": {
        "type": "string"
      }
    },
    "minimumAgentVersion": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+(\\.\\d+)?$"
    },
    "version": {
      "type": "object",
      "additionalProperties": false,
      "description": "Always update this when you release your task, so that the agents utilise the latest code.",
      "required": [
        "Major",
        "Minor",
        "Patch"
      ],
      "properties": {
        "Major": {
          "type": "number"
        },
        "Minor": {
          "type": [
            "number",
            "string"
          ]
        },
        "Patch": {
          "type": [
            "number",
            "string"
          ]
        }
      }
    },
    "instanceNameFormat": {
      "type": "string",
      "description": "This is how the task will be displayed within the build step list - you can use variable values by using $(variablename)"
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "label",
          "type"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "The variable name to use to store the user-supplied value",
            "pattern": "^[A-Za-z][A-Za-z0-9]*$"
          },
          "label": {
            "type": "string",
            "description": "The text displayed to the user for the input label"
          },
          "type": {
            "type": "string",
            "description": "The type that dictates the control rendered to the user.",
            "enum": [
              "boolean",
              "connectedService:ServiceType",
              "connectedService:AzureRM",
              "connectedService:Azure",
              "connectedService:Azure:Certificate,UsernamePassword",
              "connectedService:Chef",
              "connectedService:ssh",
              "connectedService:Generic",
              "connectedService:Jenkins",
              "connectedService:servicefabric",
              "filePath",
              "multiLine",
              "pickList",
              "radio",
              "string"
            ]
          },
          "defaultValue": {
            "type": [
              "string",
              "boolean"
            ],
            "description": "The default value to apply to this input."
          },
          "required": {
            "type": "boolean",
            "description": "Whether the input is a required field (default is false).",
            "default": false
          },
          "helpMarkDown": {
            "type": "string",
            "description": "Help to be displayed when hovering over the help icon for the input. To display URLs use the format [Text To Display](http://Url)"
          },
          "groupName": {
            "type": "string",
            "description": "Setting this to the name of a group defined in 'groups' will place the input into that group."
          },
          "visibleRule": {
            "type": "string",
            "description": "Allow's you to define a rule which dictates when the input will be visible to a user, for example \"variableName = value\""
          },
          "properties": {
            "type": "object",
            "properties": {
              "EditableOptions": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              }
            }
          },
          "options": {
            "type": "object",
            "additionalProperties": true
          }
        }
      }
    },
    "dataSourceBindings": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "target": {
            "type": "string"
          },
          "endpointId": {
            "type": "string"
          },
          "dataSourceName": {
            "type": "string"
          },
          "parameters": {
            "type": "object"
          },
          "resultTemplate": {
            "type": "string"
          }
        }
      }
    },
    "sourceDefinitions": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "target": {
            "type": "string"
          },
          "endpoint": {
            "type": "string"
          },
          "selector": {
            "type": "string"
          },
          "keySelector": {
            "type": "string"
          },
          "authKey": {
            "type": "string"
          }
        }
      }
    },
    "execution": {
      "type": "object",
      "additionalProperties": false,
      "description": "Execution options for this task",
      "properties": {
        "Node": {
          "$ref": "#/definitions/executionObject"
        },
        "Bash": {
          "$ref": "#/definitions/executionObject"
        },
        "AzurePowerShell": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell3": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShellExe": {
          "$ref": "#/definitions/executionObject"
        },
        "Process": {
          "$ref": "#/definitions/executionObject"
        },
        "RM:ManualIntervention": {
          "$ref": "#/definitions/executionObject"
        }
      }
    },
    "messages": {
      "type": "object"
    },
    "$schema": {
      "type": "string"
    }
  },
  "definitions": {
    "executionObject": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "target": {
          "type": "string",
          "description": "The target file to be executed. You can use variables here in brackets e.g. $(currentDirectory)\filename.ps1"
        },
        "argumentFormat": {
          "type": "string"
        },
        "workingDirectory": {
          "type": "string",
          "description": "The directory to execute the task from e.g. $(currentDirectory)"
        },
        "modifyEnvironment": {
          "type": [
            "boolean",
            "string"
          ]
        },
        "platforms": {
          "type": "array",
          "items": {
            "enum": [
              "windows"
            ]
          }
        }
      }
    }
  }
}

=== microsoft/azure-pipelines-tasks/Tasks/AzureFileCopy/task.json
{
  "id": "EB72CB01-A7E5-427B-A8A1-1B31CCAC8A43",
  "name": "AzureFileCopy",
  "friendlyName": "Azure File Copy",
  "description": "Copy files to Azure blob or VM(s)",
  "helpMarkDown": "[More Information](https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/AzureFileCopy/README.md)",
  "category": "Deploy",
  "visibility": [
    "Preview",
    "Build",
    "Release"
  ],
  "author": "Microsoft Corporation",
  "version": {
    "Major": 1,
    "Minor": 0,
    "Patch": 3
  },
  "demands": [
    "azureps"
  ],
  "minimumAgentVersion": "1.85.0",
  "inputs": [
    {
      "name": "ConnectedServiceName",
      "type": "connectedService:Azure",
      "label": "Azure Subscription",
      "defaultValue": "",
      "required": true,
      "helpMarkDown": "Azure subscription to target for copying the files."
    },
    {
      "name": "SourcePath",
      "type": "string",
      "label": "Source",
      "defaultValue": "",
      "required": true,
      "helpMarkDown": "Absolute path of the source folder, or file on the local machine, or a UNC share. Expression should return a single folder or a file."
    },
    {
      "name": "StorageAccount",
      "type": "string",
      "label": "Storage Account",
      "defaultValue": "",
      "required": true,
      "helpMarkDown": "Specify a pre-existing storage account. It is also used as an intermediary for copying files to Azure VMs"
    },
    {
      "name": "Destination",
      "type": "pickList",
      "label": "Destination",
      "defaultValue": "",
      "required": true,
      "options": {
        "AzureBlob": "Azure Blob",
        "AzureVMs": "Azure VMs"
      },
      "helpMarkDown": "Select the destination, either Azure Blob or Azure VMs."
    },
    {
      "name": "ContainerName",
      "type": "string",
      "label": "Container Name",
      "defaultValue": "",
      "required": true,
      "helpMarkDown": "Name of the Container for uploading the files. Default is to create a container automatically.",
      "visibleRule": "Destination = AzureBlob"
    },
    {
      "name": "BlobPrefix",
      "type": "string",
      "label": "Blob Prefix",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "Useful for filtering files, for example, append build number to all the blobs to download files from that build only.",
      "visibleRule": "Destination = AzureBlob"
    },
    {
      "name": "EnvironmentName",
      "type": "pickList",
      "label": "Resource Group",
      "defaultValue": "",
      "required": true,
      "helpMarkDown": "Name of the target Resource Group for copying the files to.​",
      "visibleRule": "Destination = AzureVMs"
    },
    {
      "name":"ResourceFilteringMethod",
      "type":"radio",
      "label":"Select Machines By",
      "required":false,
      "defaultValue":"machineNames",
      "options": {
         "machineNames":"Machine Names",
         "tags":"Tags"
       },
      "visibleRule": "Destination = AzureVMs"
    },
    {
      "name": "MachineNames",
      "type": "string",
      "label": "Copy to Machines",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "If not specified, all machines in the Machine Group are selected. Format for Machine Names: \"Provide a comma separated list of machine names/FQDN. Example- TextBox.fareast.microsoft.corp.com, 192.168.12.34.\" Format for Tags: \"Provide a semi-colon separated list of key:value pairs. Example Role:Web;OS:Win7 - returns machines with either of the tags.\"",
      "visibleRule": "Destination = AzureVMs"
    },
    {
      "name": "TargetPath",
      "type": "string",
      "label": "Destination Folder",
      "defaultValue": "",
      "required": true,
      "helpMarkDown": "Local path on the target machines for copying the files from the source. Environment variable can be used like $env:windir\\BudgetIT\\Web.",
      "visibleRule": "Destination = AzureVMs"
    },
    {
      "name": "CleanTargetBeforeCopy",
      "type": "boolean",
      "label": "Clean Target",
      "defaultValue": "false",
      "required": false,
      "helpMarkDown": "Setting it to true will clean-up the destination folder before copying the files.",
      "visibleRule": "Destination = AzureVMs"
    },
    {
      "name": "CopyFilesInParallel",
      "type": "boolean",
      "label": "Copy Files in Parallel",
      "defaultValue": "true",
      "required": false,
      "helpMarkDown": "Setting it to true will copy files in parallel to the target machines.",
      "visibleRule": "Destination = AzureVMs"
    }
  ],
  "sourceDefinitions": [
    {
      "target": "EnvironmentName",
      "endpoint": "/$(system.teamProject)/_apis/vslabs/environments",
      "selector": "jsonpath:$.value[*].name",
      "authKey": "tfs:DevTestLabs"
    }
  ],
  "instanceNameFormat": "$(Destination) File Copy",
  "execution": {
    "AzurePowerShell": {
      "target": "$(currentDirectory)\\AzureFileCopy.ps1",
      "argumentFormat": "",
      "workingDirectory": "$(currentDirectory)"
    }
  }
}

=== microsoft/azure-pipelines-tasks/Tasks/ManualIntervention/task.loc.json
{
  "id": "BCB64569-D51A-4AF0-9C01-EA5D05B3B622",
  "name": "ManualIntervention",
  "friendlyName": "ms-resource:loc.friendlyName",
  "description": "ms-resource:loc.description",
  "helpMarkDown": "ms-resource:loc.helpMarkDown",
  "category": "Deploy",
  "visibility": [
    "Release"
  ],
  "author": "Microsoft Corporation",
  "runsOn": [
    "Server"
  ],
  "version": {
    "Major": 8,
    "Minor": 0,
    "Patch": 0
  },
  "inputs": [
    {
      "name": "instructions",
      "type": "multiLine",
      "label": "ms-resource:loc.input.label.instructions",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.instructions",
      "properties": {
        "resizable": "true",
        "rows": "10",
        "maxLength": "500"
      }
    }
  ],
  "instanceNameFormat": "ms-resource:loc.instanceNameFormat",
  "execution": {
    "RM:ManualIntervention": {}
  }
}
